const express = require('express')
const expressJoi = require('@escook/express-joi')
const { insert_house_schema } = require('../schema/inserthouse')
const Router = express.Router()
const { showdata } = require('../router_handler/warehouse')
Router.get('/warehouse/showall', showdata)
const { housepage } = require('../router_handler/warehouse')
Router.get('/warehouse/page', housepage)
const { addhouse } = require('../router_handler/warehouse')
Router.post('/warehouse/add', expressJoi(insert_house_schema), addhouse)
const { delhouse } = require('../router_handler/warehouse')
Router.post('/warehouse/del', delhouse)
const { searchhouse } = require('../router_handler/warehouse')
Router.post('/warehouse/search', searchhouse)
module.exports = Router
